### ISSUE TITLE
max values no working

### ISSUE THREAD

**Issue by Andreibv** [AleksandrNikolaevich/react-native-money-input#1]
When the user type 20 digits, the values are setting with empty.
Is possible use more digits?

**Comment by AleksandrNikolaevich** [comment]
@Andreibv  Could you give me example of usage this package in your project and steps for reproduce wrong behavior?

**Comment by Andreibv** [comment]
https://github.com/user-attachments/assets/59da9b3d-b9ca-41ff-b627-0930298a06d9

if i type one more digit, after that the value is setting empty 

im using
"react-native": "0.74.2",
"@alexzunik/react-native-money-input": "^0.3.3",

**Comment by AleksandrNikolaevich** [comment]
@Andreibv Sorry for a long wait. 
I updated the library, now you can use 36 characters as integer part.
Unfortunately, the library has limitations (see [here](https://github.com/AleksandrNikolaevich/react-native-money-input?tab=readme-ov-file#%EF%B8%8F-limitations))
